-- Oxygen Wellness Center — esquema base
-- Convenciones: snake_case, BIGINT GENERATED BY DEFAULT AS IDENTITY, TIMESTAMPTZ DEFAULT now(),
-- trigger set_updated_at() en toda tabla con updated_at (mismo patrón que Sianna Travel / Wolf Daniels).

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ============================================================
-- Catálogo
-- ============================================================

CREATE TABLE IF NOT EXISTS sucursales (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  direccion TEXT,
  activo BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
DROP TRIGGER IF EXISTS trg_sucursales_updated ON sucursales;
CREATE TRIGGER trg_sucursales_updated BEFORE UPDATE ON sucursales
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS salones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sucursal_id BIGINT NOT NULL REFERENCES sucursales(id) ON DELETE RESTRICT,
  nombre TEXT NOT NULL,
  capacidad_maxima INTEGER NOT NULL DEFAULT 0,
  activo BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
DROP TRIGGER IF EXISTS trg_salones_updated ON salones;
CREATE TRIGGER trg_salones_updated BEFORE UPDATE ON salones
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS disciplinas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL UNIQUE,
  color TEXT NOT NULL DEFAULT '#1B6E68',
  descripcion TEXT,
  activo BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
DROP TRIGGER IF EXISTS trg_disciplinas_updated ON disciplinas;
CREATE TRIGGER trg_disciplinas_updated BEFORE UPDATE ON disciplinas
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS coaches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  bio TEXT,
  foto_url TEXT,
  activo BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
DROP TRIGGER IF EXISTS trg_coaches_updated ON coaches;
CREATE TRIGGER trg_coaches_updated BEFORE UPDATE ON coaches
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS coach_disciplinas (
  coach_id BIGINT NOT NULL REFERENCES coaches(id) ON DELETE CASCADE,
  disciplina_id BIGINT NOT NULL REFERENCES disciplinas(id) ON DELETE CASCADE,
  PRIMARY KEY (coach_id, disciplina_id)
);

-- ============================================================
-- Identidad del cliente
-- ============================================================

CREATE TABLE IF NOT EXISTS clientes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  whatsapp TEXT NOT NULL UNIQUE,
  email TEXT,
  qr_token UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  estado TEXT NOT NULL DEFAULT 'activo',
  consentimiento_marketing BOOLEAN NOT NULL DEFAULT false,
  notas_internas TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
DROP TRIGGER IF EXISTS trg_clientes_updated ON clientes;
CREATE TRIGGER trg_clientes_updated BEFORE UPDATE ON clientes
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ============================================================
-- Agenda y reservas
-- ============================================================

CREATE TABLE IF NOT EXISTS clases (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  disciplina_id BIGINT NOT NULL REFERENCES disciplinas(id) ON DELETE RESTRICT,
  coach_id BIGINT NOT NULL REFERENCES coaches(id) ON DELETE RESTRICT,
  salon_id BIGINT NOT NULL REFERENCES salones(id) ON DELETE RESTRICT,
  fecha DATE NOT NULL,
  hora_inicio TIME NOT NULL,
  duracion_minutos INTEGER NOT NULL DEFAULT 50,
  capacidad_maxima INTEGER NOT NULL,
  nivel TEXT,
  descripcion TEXT,
  estado TEXT NOT NULL DEFAULT 'programada', -- programada | cancelada | completada
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
DROP TRIGGER IF EXISTS trg_clases_updated ON clases;
CREATE TRIGGER trg_clases_updated BEFORE UPDATE ON clases
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE INDEX IF NOT EXISTS idx_clases_fecha ON clases(fecha);
CREATE INDEX IF NOT EXISTS idx_clases_coach ON clases(coach_id);

CREATE TABLE IF NOT EXISTS promociones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  tipo TEXT NOT NULL,
  reglas JSONB NOT NULL DEFAULT '{}'::jsonb,
  beneficio JSONB NOT NULL DEFAULT '{}'::jsonb,
  vigencia_inicio DATE,
  vigencia_fin DATE,
  uso_maximo_por_cliente INTEGER,
  uso_maximo_global INTEGER,
  combinable BOOLEAN NOT NULL DEFAULT false,
  activo BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
DROP TRIGGER IF EXISTS trg_promociones_updated ON promociones;
CREATE TRIGGER trg_promociones_updated BEFORE UPDATE ON promociones
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- La lista de espera es un estado de reserva, no una tabla aparte (evita lógica duplicada).
CREATE TABLE IF NOT EXISTS reservas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clase_id BIGINT NOT NULL REFERENCES clases(id) ON DELETE CASCADE,
  cliente_id BIGINT NOT NULL REFERENCES clientes(id) ON DELETE CASCADE,
  estado TEXT NOT NULL DEFAULT 'confirmada', -- confirmada | lista_espera | cancelada | no_show | asistio
  posicion_espera INTEGER,
  origen TEXT NOT NULL DEFAULT 'web', -- web | recepcion | admin
  promocion_id BIGINT REFERENCES promociones(id) ON DELETE SET NULL,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (clase_id, cliente_id)
);
DROP TRIGGER IF EXISTS trg_reservas_updated ON reservas;
CREATE TRIGGER trg_reservas_updated BEFORE UPDATE ON reservas
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE INDEX IF NOT EXISTS idx_reservas_clase ON reservas(clase_id);
CREATE INDEX IF NOT EXISTS idx_reservas_cliente ON reservas(cliente_id);

CREATE TABLE IF NOT EXISTS checkins (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reserva_id BIGINT NOT NULL REFERENCES reservas(id) ON DELETE CASCADE,
  cliente_id BIGINT NOT NULL REFERENCES clientes(id) ON DELETE CASCADE,
  metodo TEXT NOT NULL DEFAULT 'qr', -- qr | manual
  validaciones JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_checkins_cliente ON checkins(cliente_id);

-- ============================================================
-- Comercial: membresías, paquetes, saldo, pagos, promociones
-- ============================================================

CREATE TABLE IF NOT EXISTS membresias (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  tipo TEXT NOT NULL, -- ilimitada | por_clases
  vigencia_dias INTEGER NOT NULL,
  clases_incluidas INTEGER,
  precio NUMERIC(10,2) NOT NULL DEFAULT 0,
  activo BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
DROP TRIGGER IF EXISTS trg_membresias_updated ON membresias;
CREATE TRIGGER trg_membresias_updated BEFORE UPDATE ON membresias
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS paquetes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  num_clases INTEGER NOT NULL,
  vigencia_dias INTEGER NOT NULL,
  precio NUMERIC(10,2) NOT NULL DEFAULT 0,
  activo BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
DROP TRIGGER IF EXISTS trg_paquetes_updated ON paquetes;
CREATE TRIGGER trg_paquetes_updated BEFORE UPDATE ON paquetes
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS suscripciones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente_id BIGINT NOT NULL REFERENCES clientes(id) ON DELETE CASCADE,
  membresia_id BIGINT NOT NULL REFERENCES membresias(id) ON DELETE RESTRICT,
  fecha_inicio DATE NOT NULL,
  fecha_fin DATE NOT NULL,
  estado TEXT NOT NULL DEFAULT 'activa', -- activa | vencida | cancelada
  auto_renovacion BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
DROP TRIGGER IF EXISTS trg_suscripciones_updated ON suscripciones;
CREATE TRIGGER trg_suscripciones_updated BEFORE UPDATE ON suscripciones
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Tabla genérica de crédito: hoy resuelve paquetes de clases, mañana resuelve puntos/recompensas
-- sin cambiar el esquema (ver documento de diseño, sección "Modelo conceptual de datos").
CREATE TABLE IF NOT EXISTS movimientos_saldo (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente_id BIGINT NOT NULL REFERENCES clientes(id) ON DELETE CASCADE,
  tipo TEXT NOT NULL, -- compra | consumo | ajuste | promocion | puntos
  cantidad INTEGER NOT NULL,
  referencia_tipo TEXT, -- paquete | reserva | promocion | ajuste_manual
  referencia_id BIGINT,
  fecha_expiracion DATE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_movimientos_saldo_cliente ON movimientos_saldo(cliente_id);

CREATE TABLE IF NOT EXISTS redenciones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  promocion_id BIGINT NOT NULL REFERENCES promociones(id) ON DELETE CASCADE,
  cliente_id BIGINT NOT NULL REFERENCES clientes(id) ON DELETE CASCADE,
  reserva_id BIGINT REFERENCES reservas(id) ON DELETE SET NULL,
  pago_id BIGINT,
  fecha TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS pagos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente_id BIGINT NOT NULL REFERENCES clientes(id) ON DELETE CASCADE,
  concepto TEXT NOT NULL,
  referencia_tipo TEXT, -- paquete | membresia | clase_suelta
  referencia_id BIGINT,
  monto NUMERIC(10,2) NOT NULL,
  metodo TEXT NOT NULL DEFAULT 'efectivo', -- efectivo | tarjeta | transferencia | en_linea
  estado TEXT NOT NULL DEFAULT 'pagado',
  fecha TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_pagos_cliente ON pagos(cliente_id);

ALTER TABLE redenciones
  ADD CONSTRAINT fk_redenciones_pago FOREIGN KEY (pago_id) REFERENCES pagos(id) ON DELETE SET NULL;

-- ============================================================
-- Usuarios internos, roles y permisos (RBAC)
-- ============================================================

CREATE TABLE IF NOT EXISTS roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL UNIQUE -- administrador | recepcion | coach
);

CREATE TABLE IF NOT EXISTS permisos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo TEXT NOT NULL UNIQUE,
  descripcion TEXT
);

CREATE TABLE IF NOT EXISTS rol_permisos (
  rol_id BIGINT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
  permiso_id BIGINT NOT NULL REFERENCES permisos(id) ON DELETE CASCADE,
  PRIMARY KEY (rol_id, permiso_id)
);

CREATE TABLE IF NOT EXISTS usuarios_internos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  rol_id BIGINT NOT NULL REFERENCES roles(id) ON DELETE RESTRICT,
  coach_id BIGINT REFERENCES coaches(id) ON DELETE SET NULL,
  activo BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
DROP TRIGGER IF EXISTS trg_usuarios_internos_updated ON usuarios_internos;
CREATE TRIGGER trg_usuarios_internos_updated BEFORE UPDATE ON usuarios_internos
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ============================================================
-- Configuración general (reglas de negocio editables sin tocar código)
-- ============================================================

CREATE TABLE IF NOT EXISTS configuracion_general (
  clave TEXT PRIMARY KEY,
  valor JSONB NOT NULL,
  descripcion TEXT,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
DROP TRIGGER IF EXISTS trg_configuracion_general_updated ON configuracion_general;
CREATE TRIGGER trg_configuracion_general_updated BEFORE UPDATE ON configuracion_general
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ============================================================
-- Auditoría genérica
-- ============================================================

CREATE TABLE IF NOT EXISTS historial (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entidad TEXT NOT NULL,
  entidad_id BIGINT,
  accion TEXT NOT NULL,
  actor_tipo TEXT NOT NULL DEFAULT 'sistema', -- cliente | staff | sistema
  actor_id BIGINT,
  detalle JSONB NOT NULL DEFAULT '{}'::jsonb,
  fecha TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_historial_entidad ON historial(entidad, entidad_id);

-- ============================================================
-- Stub para control de acceso físico futuro (sin uso todavía)
-- ============================================================

CREATE TABLE IF NOT EXISTS eventos_acceso (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente_id BIGINT REFERENCES clientes(id) ON DELETE SET NULL,
  punto_acceso TEXT,
  resultado TEXT,
  "timestamp" TIMESTAMPTZ NOT NULL DEFAULT now()
);
